config/routes.rb
Rails.application.routes.draw do
  CMS::Routes.new(self).draw

  root to: 'pages#home'
  resource :session

  namespace 'cofactor', module: nil do
    root to: 'cofactor#index'

    resources :teams
  end
end

app/models/cms/file_upload.rb
class CMS::FileUpload < ActiveRecord::Base
  self.table_name = 'file_uploads'

  mount_uploader :file, CMS::Uploader

  def self.name
    'FileUpload'
  end
end

app/models/cms/page.rb
class CMS::Page < ActiveRecord::Base
  self.table_name = 'pages'
  belongs_to :team, class_name: 'CMS::Team'

  validates :name, presence: true
  validates :url, presence: true

  def self.name
    'Page'
  end
end

app/models/cms/page_area.rb
class CMS::PageArea < ActiveRecord::Base
  self.table_name = 'page_areas'


  def self.name
    'PageArea'
  end
end

app/models/cms/team.rb
class CMS::Team < ActiveRecord::Base
  self.table_name = 'teams'
  has_many :pages, class_name: 'CMS::Page'

  def self.name
    'Team'
  end
end

app/models/oauth_user.rb
class OauthUser < SimpleDelegator

  def role
    ActiveSupport::StringInquirer.new('admin')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def signed_in?
    true
  end

  def current_user
    OauthUser.new(self)
  end
end

app/controllers/cms/file_uploads_controller.rb
class CMS::FileUploadsController < CMS::BaseController
  helper_method :subject

  protected

  def subject
    CMS::FileUpload
  end

  def file_upload_params
    params.require(:file_upload).permit(:description, :file, :name)
  end
  alias :subject_params :file_upload_params
end

app/controllers/cms/page_areas_controller.rb
class CMS::PageAreasController < CMS::BaseController
  helper_method :subject

  protected

  def subject
    CMS::PageArea
  end

  def page_area_params
    params.require(:page_area).permit(:content, :description, :name)
  end
  alias :subject_params :page_area_params
end

app/controllers/cms/pages_controller.rb
class CMS::PagesController < CMS::BaseController
  helper_method :subject

  protected

  def subject
    CMS::Page
  end

  def page_params
    params.require(:page).permit(:name, :team_id, :url)
  end
  alias :subject_params :page_params
end

app/controllers/cms/teams_controller.rb
class CMS::TeamsController < CMS::BaseController
  helper_method :subject

  protected

  def subject
    CMS::Team
  end

  def team_params
    params.require(:team).permit(:description, :name, :slug)
  end
  alias :subject_params :team_params
end

app/controllers/cofactor_controller.rb
class CofactorController < ApplicationController
  def index
    @teams = CMS::Team.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
    render layout: false
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  def show
    @team = CMS::Team.find_by_slug!(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def markdown text
    Markdown.render(text.to_s).html_safe
  end
end

app/views/cms/file_uploads/_fields.html.slim
.form-group
  = f.label :name, class: 'col-md-2 control-label'
  .col-lg-10
    = f.text_field :name, class: 'form-control'
.form-group
  = f.label :file, class: 'col-md-2 control-label'
  .col-lg-10
    = f.file_field :file, class: 'form-control'
.form-group
  = f.label :description, class: 'col-md-2 control-label'
  .col-lg-10
    = f.text_area :description, class: 'form-control'
.form-group
  .col-lg-offset-2.col-lg-10= f.submit 'Save', class: 'btn btn-primary', :'data-disable-with' => 'Saving...'

app/views/cms/file_uploads/edit.html.slim
.panel-heading: .panel-title: h5 Edit file upload

.panel-body
  = form_for @file_upload, url: cms_file_upload_path(@file_upload), html: {class: 'form-horizontal'} do |f|
    = render partial: 'fields', locals: { f: f }

app/views/cms/file_uploads/index.html.slim
.panel-heading: .panel-title: h5 File uploads

.panel-body
  = link_to 'New file upload', new_cms_file_upload_path

table.table
  thead
    tr
      th Id
      th Name
      th File
      th Description
      th

  tbody
    - @file_uploads.each do |file_upload|
      tr
        td= file_upload.id
        td= file_upload.name
        td
          img src: file_upload.file
        td= file_upload.description
        td
          span<>= link_to 'Edit', edit_cms_file_upload_path(file_upload)
          span<>= link_to 'Destroy', cms_file_upload_path(file_upload), confirm: 'are you sure?', method: 'delete'

  = paginate @file_uploads

app/views/cms/file_uploads/new.html.slim
.panel-heading: .panel-title: h5 New file upload

.panel-body
  = form_for @file_upload, url: cms_file_uploads_path, html: {class: 'form-horizontal'} do |f|
    = render partial: 'fields', locals: { f: f }

app/views/cms/file_uploads/show.html.slim
.panel-heading: .panel-title: h5 Showing file upload #{@file_upload.id}

.panel-body
  dl
    dt Name
    dd= @file_upload.name
    dt File
    dd= @file_upload.file
    dt Description
    dd= markdown @file_upload.description

app/views/cms/page_areas/_fields.html.slim
.form-group
  = f.label :name, class: 'col-md-2 control-label'
  .col-lg-10
    = f.text_field :name, class: 'form-control'
.form-group
  = f.label :description, class: 'col-md-2 control-label'
  .col-lg-10
    = f.text_field :description, class: 'form-control'
.form-group
  = f.label :content, class: 'col-md-2 control-label'
  .col-lg-10
    = f.text_area :content, class: 'form-control'
.form-group
  .col-lg-offset-2.col-lg-10= f.submit 'Save', class: 'btn btn-primary', :'data-disable-with' => 'Saving...'

app/views/cms/page_areas/edit.html.slim
.panel-heading: .panel-title: h5 Edit page area

.panel-body
  = form_for @page_area, url: cms_page_area_path(@page_area), html: {class: 'form-horizontal'} do |f|
    = render partial: 'fields', locals: { f: f }

app/views/cms/page_areas/index.html.slim
.panel-heading: .panel-title: h5 Page areas

.panel-body
  = link_to 'New page area', new_cms_page_area_path

table.table
  thead
    tr
      th Id
      th Name
      th Description
      th Content
      th

  tbody
    - @page_areas.each do |page_area|
      tr
        td= page_area.id
        td= page_area.name
        td= page_area.description
        td= page_area.content
        td
          span<>= link_to 'Edit', edit_cms_page_area_path(page_area)
          span<>= link_to 'Destroy', cms_page_area_path(page_area), confirm: 'are you sure?', method: 'delete'

  = paginate @page_areas

app/views/cms/page_areas/new.html.slim
.panel-heading: .panel-title: h5 New page area

.panel-body
  = form_for @page_area, url: cms_page_areas_path, html: {class: 'form-horizontal'} do |f|
    = render partial: 'fields', locals: { f: f }

app/views/cms/page_areas/show.html.slim
.panel-heading: .panel-title: h5 Showing page area #{@page_area.id}

.panel-body
  dl
    dt Name
    dd= @page_area.name
    dt Description
    dd= @page_area.description
    dt Content
    dd= @page_area.content

app/views/cms/pages/_fields.html.slim
.form-group
  = f.label :name, class: 'col-md-2 control-label'
  .col-lg-10
    = f.text_field :name, class: 'form-control'
.form-group
  = f.label :url, class: 'col-md-2 control-label'
  .col-lg-10
    = f.text_field :url, class: 'form-control'
.form-group
  = f.label :team_id, class: 'col-md-2 control-label'
  .col-lg-10
    = f.select :team_id, CMS::Team.all.collect {|r| [ r.name, r.id ] }, class: 'form-control'
.form-group
  .col-lg-offset-2.col-lg-10= f.submit 'Save', class: 'btn btn-primary', :'data-disable-with' => 'Saving...'

app/views/cms/pages/edit.html.slim
.panel-heading: .panel-title: h5 Edit page

.panel-body
  = form_for @page, url: cms_page_path(@page), html: {class: 'form-horizontal'} do |f|
    = render partial: 'fields', locals: { f: f }

app/views/cms/pages/index.html.slim
.panel-heading: .panel-title: h5 Pages

.panel-body
  = link_to 'New page', new_cms_page_path

table.table
  thead
    tr
      th Id
      th Name
      th Url
      th Team
      th

  tbody
    - @pages.each do |page|
      tr
        td= page.id
        td= page.name
        td= page.url
        td
          - if page.team.present?
            = link_to page.team.name, cms_team_path(page.team)
        td
          span<>= link_to 'Edit', edit_cms_page_path(page)
          span<>= link_to 'Destroy', cms_page_path(page), confirm: 'are you sure?', method: 'delete'

  = paginate @pages

app/views/cms/pages/new.html.slim
.panel-heading: .panel-title: h5 New page

.panel-body
  = form_for @page, url: cms_pages_path, html: {class: 'form-horizontal'} do |f|
    = render partial: 'fields', locals: { f: f }

app/views/cms/pages/show.html.slim
.panel-heading: .panel-title: h5 Showing page #{@page.id}

.panel-body
  dl
    dt Name
    dd= @page.name
    dt Url
    dd= @page.url
    dt Team
    dd= @page.team.try(:name)

app/views/cms/teams/_fields.html.slim
.form-group
  = f.label :name, class: 'col-md-2 control-label'
  .col-lg-10
    = f.text_field :name, class: 'form-control'
.form-group
  = f.label :description, class: 'col-md-2 control-label'
  .col-lg-10
    = f.text_area :description, class: 'form-control'
.form-group
  = f.label :slug, class: 'col-md-2 control-label'
  .col-lg-10
    = f.text_field :slug, class: 'form-control'
.form-group
  .col-lg-offset-2.col-lg-10= f.submit 'Save', class: 'btn btn-primary', :'data-disable-with' => 'Saving...'

app/views/cms/teams/edit.html.slim
.panel-heading: .panel-title: h5 Edit team

.panel-body
  = form_for @team, url: cms_team_path(@team), html: {class: 'form-horizontal'} do |f|
    = render partial: 'fields', locals: { f: f }

app/views/cms/teams/index.html.slim
.panel-heading: .panel-title: h5 Teams

.panel-body
  = link_to 'New team', new_cms_team_path

table.table
  thead
    tr
      th Id
      th Name
      th Description
      th Slug
      th

  tbody
    - @teams.each do |team|
      tr
        td= team.id
        td= team.name
        td= team.description
        td= team.slug
        td
          span<>= link_to 'Edit', edit_cms_team_path(team)
          span<>= link_to 'Destroy', cms_team_path(team), confirm: 'are you sure?', method: 'delete'

  = paginate @teams

app/views/cms/teams/new.html.slim
.panel-heading: .panel-title: h5 New team

.panel-body
  = form_for @team, url: cms_teams_path, html: {class: 'form-horizontal'} do |f|
    = render partial: 'fields', locals: { f: f }

app/views/cms/teams/show.html.slim
.panel-heading: .panel-title: h5 Showing team #{@team.id}

.panel-body
  dl
    dt Name
    dd= @team.name
    dt Description
    dd= markdown @team.description
    dt Slug
    dd= @team.slug

app/views/cofactor/index.html.slim
.container style="max-width: 670px"
  h1 Empirical Teams
  p Empirical is an open source organization composed of teams of contributors. Each team is responsible for a certain part of the site. Explore each team to see what our contributors are building!

  - @teams.each do |team|
    hr
    .team-item
      h2= link_to team.name, cofactor_team_path(team.slug) 
      p= markdown team.description.to_s

  button= link_to 'Create a new team', new_cms_team_path 

app/views/layouts/application.html.slim
html
  head
    = stylesheet_link_tag 'bootstrap'
    = stylesheet_link_tag 'application'
    = javascript_include_tag '//code.jquery.com/jquery-git2.min.js'
    = javascript_include_tag 'bootstrap/tab'
    link href="http://fonts.googleapis.com/css?family=Libre+Baskerville|Open+Sans" rel="stylesheet" type="text/css"
    scss:
      @mixin baskerville { font-family: 'Libre Baskerville', serif }
      @mixin open-sans   { font-family: 'Open Sans', sans-serif }

      h1, h2, h3, h4, h5, h6, .h1, .h2, .h3, .h4, .h5, .h6 {
        @include baskerville;
      }
  body
    = yield